// Code generated by protoc-gen-go.
// source: node.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	node.proto

It has these top-level messages:
	FindRecentNodeReq
	FindNode
*/
package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type FindRecentNodeReq struct {
	Timeout          *int32  `protobuf:"varint,1,opt" json:"Timeout,omitempty"`
	NodeId           *string `protobuf:"bytes,2,opt" json:"NodeId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FindRecentNodeReq) Reset()         { *m = FindRecentNodeReq{} }
func (m *FindRecentNodeReq) String() string { return proto.CompactTextString(m) }
func (*FindRecentNodeReq) ProtoMessage()    {}

func (m *FindRecentNodeReq) GetTimeout() int32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

func (m *FindRecentNodeReq) GetNodeId() string {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return ""
}

type FindNode struct {
	Timeout          *int32  `protobuf:"varint,1,opt" json:"Timeout,omitempty"`
	NodeId           *string `protobuf:"bytes,2,opt" json:"NodeId,omitempty"`
	FindId           *string `protobuf:"bytes,3,opt" json:"FindId,omitempty"`
	IsProxy          *bool   `protobuf:"varint,4,opt" json:"IsProxy,omitempty"`
	ProxyId          *string `protobuf:"bytes,5,opt" json:"ProxyId,omitempty"`
	Addr             *string `protobuf:"bytes,6,opt" json:"Addr,omitempty"`
	TcpPort          *int32  `protobuf:"varint,7,opt" json:"TcpPort,omitempty"`
	UdpPort          *int32  `protobuf:"varint,8,opt" json:"UdpPort,omitempty"`
	Status           *int32  `protobuf:"varint,9,opt" json:"Status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FindNode) Reset()         { *m = FindNode{} }
func (m *FindNode) String() string { return proto.CompactTextString(m) }
func (*FindNode) ProtoMessage()    {}

func (m *FindNode) GetTimeout() int32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

func (m *FindNode) GetNodeId() string {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return ""
}

func (m *FindNode) GetFindId() string {
	if m != nil && m.FindId != nil {
		return *m.FindId
	}
	return ""
}

func (m *FindNode) GetIsProxy() bool {
	if m != nil && m.IsProxy != nil {
		return *m.IsProxy
	}
	return false
}

func (m *FindNode) GetProxyId() string {
	if m != nil && m.ProxyId != nil {
		return *m.ProxyId
	}
	return ""
}

func (m *FindNode) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

func (m *FindNode) GetTcpPort() int32 {
	if m != nil && m.TcpPort != nil {
		return *m.TcpPort
	}
	return 0
}

func (m *FindNode) GetUdpPort() int32 {
	if m != nil && m.UdpPort != nil {
		return *m.UdpPort
	}
	return 0
}

func (m *FindNode) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func init() {
}
