// Code generated by protoc-gen-go.
// source: common.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	BaseMsg
*/
package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type BaseMsg struct {
	MsgType          *int32 `protobuf:"varint,1,opt" json:"MsgType,omitempty"`
	Timeout          *int32 `protobuf:"varint,2,opt" json:"Timeout,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BaseMsg) Reset()         { *m = BaseMsg{} }
func (m *BaseMsg) String() string { return proto.CompactTextString(m) }
func (*BaseMsg) ProtoMessage()    {}

func (m *BaseMsg) GetMsgType() int32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *BaseMsg) GetTimeout() int32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

func init() {
}
